import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/header";

const heroNew = localFont({
  src: [
    {
      path: "../../public/fonts/HeroNew-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/HeroNew-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/HeroNew-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/HeroNew-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/HeroNew-Medium.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/HeroNew-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/HeroNew-Bold.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/HeroNew-ExtraBold.woff2",
      weight: "800",
      style: "italic",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const loca_data = {
  header_data: {
    id: "uuid PRIMARY KEY",
    name: "Bosq Ergonomics",
    slug: "/",
    logoUrl: "images/brand-logo.svg",
    logoWhiteUrl: "images/brand-logo.svg",
    description: "text",
    websiteUrl: "https://bosq.ae/",
    countryOfOrigin: "char(2) (ISO country code)",
    establishedYear: "2025",
    specialties: "text[] (e.g., ['ergonomic chairs', 'office desks'])",
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
    seoTitle: "Bosq Ergonomics",
    seoDescription: "text",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  navigation_data: [
    {
      id: "01",
      name: "Home",
      slug: "/",
    },
    {
      id: "02",
      name: "Shop All",
      slug: "/product",
    },
    {
      id: "03",
      name: "Office Chairs",
      slug: "/office-chair",
    },
    {
      id: "04",
      name: "Workstations",
      slug: "/",
    },
    {
      id: "05",
      name: "Storage",
      slug: "/",
    },
    {
      id: "06",
      name: "Contact",
      slug: "/",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${heroNew.className} antialiased`}
    >
      <body>
        <Header
          headerData={loca_data.header_data}
          navigationData={loca_data.navigation_data}
        />
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
