import Script from "next/script";
import localFont from "next/font/local";
import { Cairo } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./../globals.css";
import { cn } from "@/lib/utils";
import { locales, localeDirection } from "../../il8n/config";
import ReduxProvider from "@/store/provider";
import { Toaster } from "sonner";
import AuthSyncProvider from "@/components/providers/AuthSyncProvider";
import ScrollRestoration from "@/components/providers/ScrollRestoration";
import RecaptchaProvider from "@/app/[locale]/(public)/CaptchaWrapper";

const heroNew = localFont({
  src: [
    {
      path: "../../../public/fonts/HeroNew-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Medium.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Bold.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-ExtraBold.woff2",
      weight: "800",
      style: "italic",
    },
  ],
  display: "swap",
});

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

// Arabic Google Font - Cairo
const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cairo",
  display: "swap",
});

export const metadata = {
  title: "Bosq",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const resolvedParams = await params;

  const locale = resolvedParams.locale;
  const dir = localeDirection[resolvedParams.locale];
  const messages = await getMessages({ locale });

  const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
  const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID;
  return (
    <html lang={locale} dir={dir} className={cn(locale === "ar" ? cairo.className : heroNew.className, "antialiased")}>
      <head>
        <link rel="preconnect" href={apiBaseUrl} />
        <link rel="dns-prefetch" href={apiBaseUrl} />
        {GTM_ID && (
          <Script
            id="gtm-script"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${GTM_ID}');`,
            }}
          />
        )}
      </head>
      <body className={locale === "ar" ? "font-cairo" : "font-hero"}>
        {GTM_ID && (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            />
          </noscript>
        )}
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <RecaptchaProvider>
              <AuthSyncProvider />
              <ScrollRestoration />
              <NuqsAdapter>{children}</NuqsAdapter>
              <Toaster position={locale === "ar" ? "bottom-left" : "bottom-right"} richColors closeButton visibleToasts={1} />
            </RecaptchaProvider>
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
