import localFont from "next/font/local";
import "./../globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const heroNew = localFont({
  src: [
    {
      path: "../../../public/fonts/HeroNew-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Medium.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Bold.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-ExtraBold.woff2",
      weight: "800",
      style: "italic",
    },
  ],
});

export const metadata = {
  title: "Bosq",
  description: "Generated by create next app",
};

const local_data = {
  header_data: {
    id: "uuid PRIMARY KEY",
    name: "Bosq Ergonomics",
    slug: "/",
    logoUrl: "images/brand-logo.svg",
    logoWhiteUrl: "images/brand-logo.svg",
    description: "text",
    websiteUrl: "https://bosq.ae/",
    countryOfOrigin: "char(2) (ISO country code)",
    establishedYear: "2025",
    specialties: "text[] (e.g., ['ergonomic chairs', 'office desks'])",
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
    seoTitle: "Bosq Ergonomics",
    seoDescription: "text",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  navigation_data: [
    {
      id: "01",
      name: "Home",
      slug: "/",
    },
    {
      id: "02",
      name: "Shop All",
      slug: "/product",
    },
    {
      id: "03",
      name: "Office Chairs",
      slug: "/office-chair",
    },
    {
      id: "04",
      name: "Workstations",
      slug: "/",
    },
    {
      id: "05",
      name: "Storage",
      slug: "/",
    },
    {
      id: "06",
      name: "Contact",
      slug: "/",
    },
  ],
  footer_data: {
    id: "uuid PRIMARY KEY",
    name: "Bosq Ergonomics",
    slug: "/",
    logoUrl: "images/brand-logo.svg",
    logoWhiteUrl: "images/brand-logo.svg",
    address:
      "<p>AYN MUSK FOR FURNITURE CO.L.L.C<br /> Office No 133, KML Business Tower,Meydan Road,<br /> Al Qouz, Dubai P.O Box: 294568</p>",
    websiteUrl: "https://bosq.ae/",
    shop_navigation: [
      {
        id: "01",
        label: "Office Chairs",
        link: "/",
      },
      {
        id: "02",
        label: "Workstations",
        link: "/",
      },
      {
        id: "03",
        label: "Storage",
        link: "/",
      },
      {
        id: "04",
        label: "Shop All",
        link: "/",
      },
    ],
    quick_link_navigation: [
      {
        id: "01",
        label: "Home",
        link: "/",
      },
      {
        id: "02",
        label: "About",
        link: "/",
      },
      {
        id: "03",
        label: "Contact",
        link: "/",
      },
      {
        id: "04",
        label: "Projects",
        link: "/",
      },
    ],
    other_link_navigation: [
      {
        id: "01",
        label: "Ergonomic Chair Guide",
        link: "/",
      },
      {
        id: "02",
        label: "Delivery",
        link: "/",
      },
      {
        id: "03",
        label: "Material Guide",
        link: "/",
      },
      {
        id: "04",
        label: "Warranty",
        link: "/",
      },
      {
        id: "05",
        label: "F&Q",
        link: "/",
      },
      {
        id: "06",
        label: "Privacy Policy",
        link: "/",
      },
      {
        id: "07",
        label: "Terms & Conditions",
        link: "/",
      },
      {
        id: "08",
        label: "Return & Refund Policy",
        link: "/",
      },
    ],
    sale_enquiry: {
      title: "For Sale Enquiry",
      phone: "+971 56 503 6378",
      email: "sales@bosq.ae",
    },
    support_enquiry: {
      title: "For Support Enquiry",
      phone: "",
      email: "support@bosq.ae",
    },
    copyright: "<p>© 2025 Bosq Ergonomics. All Rights Reserved.</p>",
    subscription_title: "<p>Stay Updated. Subscribe to Our Newsletter</p>",
    card: [
      {
        id: "01",
        name: "card",
        link: "https://www.bosq.ae/",
        media: {
          media_type: "image",
          media_path: "/images/footer-card.png",
          media_alt: "footer-card",
        },
      },
    ],
  },
  social_link_data: [
    {
      id: "01",
      name: "facebook",
      link: "https://www.facebook.com/",
      media: {
        media_type: "image",
        media_path: "/images/social-fb.svg",
        media_alt: "social-fb",
      },
    },
    {
      id: "02",
      name: "instagram",
      link: "https://www.instagram.com/",
      media: {
        media_type: "image",
        media_path: "/images/social-insta.svg",
        media_alt: "social-insta",
      },
    },
    {
      id: "03",
      name: "youtube",
      link: "https://www.youtube.com/",
      media: {
        media_type: "image",
        media_path: "/images/social-youtube.svg",
        media_alt: "social-youtube",
      },
    },
    {
      id: "04",
      name: "linkedin",
      link: "https://www.linkedin.com/",
      media: {
        media_type: "image",
        media_path: "/images/social-linkedin.svg",
        media_alt: "social-linkedin",
      },
    },
  ],
};

export default async function RootLayout({ children }) {
  const locale = "en";
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${heroNew.className} antialiased`}
    >
      <body>
        <Header
          headerData={local_data.header_data}
          navigationData={local_data.navigation_data}
        />
        <main>{children}</main>
        <Footer
          footerData={local_data.footer_data}
          socialLinkData={local_data.social_link_data}
        />
      </body>
    </html>
  );
}
