import localFont from "next/font/local";
import { Cairo } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./../globals.css";
import { cn } from "@/lib/utils";
import { locales, localeDirection } from "../../il8n/config";
import ReduxProvider from "@/store/provider";
import { Toaster } from "sonner";
import AuthSyncProvider from "@/components/providers/AuthSyncProvider";
import ScrollRestoration from "@/components/providers/ScrollRestoration";
import RecaptchaProvider from "@/app/[locale]/(public)/CaptchaWrapper";

const heroNew = localFont({
  src: [
    {
      path: "../../../public/fonts/HeroNew-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Medium.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/HeroNew-Bold.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../../public/fonts/HeroNew-ExtraBold.woff2",
      weight: "800",
      style: "italic",
    },
  ],
});

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

// Arabic Google Font - Cairo
const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cairo",
  display: "swap",
});

export const metadata = {
  title: "Bosq",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const resolvedParams = await params;

  const locale = resolvedParams.locale;
  const dir = localeDirection[resolvedParams.locale];
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} dir={dir} className={cn(locale === "ar" ? cairo.className : heroNew.className, "antialiased")}>
      <body className={locale === "ar" ? "font-cairo" : "font-hero"}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <RecaptchaProvider>
              <AuthSyncProvider />
              <ScrollRestoration />
              <NuqsAdapter>{children}</NuqsAdapter>
              <Toaster position={locale === "ar" ? "bottom-left" : "bottom-right"} richColors closeButton visibleToasts={1} />
            </RecaptchaProvider>
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
